import { User } from '../types/user';
import { Patient } from '../types/patient';
import { Encounter } from '../types/encounter';
import { DashboardSummary, EncounterTrendPoint, DiagnosisDistributionPoint, AgeDistributionPoint, SeasonalTrendPoint } from '../types/dashboard';
import { AuditLog } from '../types/audit';

export const MOCK_USERS: User[] = [
  {
    id: 0,
    email: 'superadmin@3401.com',
    name: 'SuperAdmin Authority',
    role: 'superadmin',
    designation: 'Root Security Administrator',
    phoneNumber: '+91 98201 12345',
  },
  {
    id: 1,
    email: 'admin@healthtech.gov.in',
    name: 'Dr. Rajesh Sharma',
    role: 'admin',
    designation: 'Chief Medical Administrator',
    phoneNumber: '+91 98202 54321',
  },
  {
    id: 2,
    email: 'clinician@healthtech.gov.in',
    name: 'Dr. Ananya Roy',
    role: 'clinician',
    designation: 'Telemedicine Specialist',
    phoneNumber: '+91 98203 67890',
  },
  {
    id: 3,
    email: 'nurse@healthtech.gov.in',
    name: 'Pooja Verma',
    role: 'nurse',
    designation: 'Community Health Nurse',
    phoneNumber: '+91 98204 98765',
  },
];

export const INITIAL_PATIENTS: Patient[] = [
  {
    id: 'p-1',
    patientId: 'PT-0001',
    name: 'Sunita Patil',
    age: 42,
    gender: 'Female',
    registrationDate: '2026-01-12T09:30:00Z',
    status: 'active',
    district: 'Raigad Rural Clinic',
    totalEncounters: 5,
    lastEncounterDate: '2026-10-04T10:15:00Z',
  },
  {
    id: 'p-2',
    patientId: 'PT-0002',
    name: 'Ramesh Kulkarni',
    age: 58,
    gender: 'Male',
    registrationDate: '2026-02-05T11:00:00Z',
    status: 'active',
    district: 'Pune PHC Hub',
    totalEncounters: 8,
    lastEncounterDate: '2026-10-05T14:20:00Z',
  },
  {
    id: 'p-3',
    patientId: 'PT-0003',
    name: 'Priyanka Jadhav',
    age: 26,
    gender: 'Female',
    registrationDate: '2026-03-18T08:45:00Z',
    status: 'active',
    district: 'Nashik Tele-center',
    totalEncounters: 3,
    lastEncounterDate: '2026-09-28T11:00:00Z',
  },
  {
    id: 'p-4',
    patientId: 'PT-0004',
    name: 'Babanrao Shinde',
    age: 67,
    gender: 'Male',
    registrationDate: '2026-04-10T14:10:00Z',
    status: 'active',
    district: 'Satara Mobile Health Unit',
    totalEncounters: 12,
    lastEncounterDate: '2026-10-06T09:30:00Z',
  },
  {
    id: 'p-5',
    patientId: 'PT-0005',
    name: 'Aarav Deshmukh',
    age: 15,
    gender: 'Other',
    registrationDate: '2026-05-22T10:00:00Z',
    status: 'active',
    district: 'Thane Tribal Welfare Center',
    totalEncounters: 2,
    lastEncounterDate: '2026-08-14T12:00:00Z',
  },
  {
    id: 'p-6',
    patientId: 'PT-0006',
    name: 'Meena Gaikwad',
    age: 34,
    gender: 'Female',
    registrationDate: '2026-06-03T16:20:00Z',
    status: 'inactive',
    district: 'Solapur Primary Clinic',
    totalEncounters: 1,
    lastEncounterDate: '2026-06-03T16:45:00Z',
  },
  {
    id: 'p-7',
    patientId: 'PT-0007',
    name: 'Vikas Bhosale',
    age: 51,
    gender: 'Male',
    registrationDate: '2026-07-15T09:15:00Z',
    status: 'active',
    district: 'Kolhapur Sub-center',
    totalEncounters: 4,
    lastEncounterDate: '2026-10-02T16:00:00Z',
  },
  {
    id: 'p-8',
    patientId: 'PT-0008',
    name: 'Kavita Salunkhe',
    age: 29,
    gender: 'Female',
    registrationDate: '2026-08-01T13:40:00Z',
    status: 'active',
    district: 'Aurangabad Health Post',
    totalEncounters: 6,
    lastEncounterDate: '2026-10-06T15:10:00Z',
  },
];

export const INITIAL_ENCOUNTERS: Encounter[] = [
  {
    id: 'enc-1',
    encounterId: 'ENC-1001',
    patientId: 'p-4',
    patientDisplayId: 'PT-0004',
    date: '2026-10-06T09:30:00Z',
    symptoms: 'Mild dizziness, elevated morning blood sugar, occasional shortness of breath',
    diagnosis: 'Type 2 Diabetes Mellitus',
    treatment: 'Metformin 500mg BID, dietary counseling, hydration plan',
    clinician: 'Dr. Ananya Roy',
    temperature: '98.4',
    bloodPressure: '138/88',
    status: 'completed',
    notes: 'Patient advised to monitor fasting levels weekly.',
  },
  {
    id: 'enc-2',
    encounterId: 'ENC-1002',
    patientId: 'p-8',
    patientDisplayId: 'PT-0008',
    date: '2026-10-06T15:10:00Z',
    symptoms: 'High grade fever with chills, body ache, joint pain for 3 days',
    diagnosis: 'Malaria (P. vivax)',
    treatment: 'Chloroquine + Primaquine regimen under supervision, Paracetamol 650mg SOS',
    clinician: 'Dr. Rajesh Sharma',
    temperature: '101.8',
    bloodPressure: '118/76',
    status: 'active',
    notes: 'Rapid diagnostic test (RDT) positive. Vector control notified.',
  },
  {
    id: 'enc-3',
    encounterId: 'ENC-1003',
    patientId: 'p-2',
    patientDisplayId: 'PT-0002',
    date: '2026-10-05T14:20:00Z',
    symptoms: 'Occipital headache, fatigue, palpitations upon exertion',
    diagnosis: 'Hypertension (Primary)',
    treatment: 'Amlodipine 5mg OD, low sodium intake, walk 30 mins daily',
    clinician: 'Dr. Ananya Roy',
    temperature: '98.6',
    bloodPressure: '150/94',
    status: 'completed',
    notes: 'Follow-up BP screening scheduled in 2 weeks.',
  },
  {
    id: 'enc-4',
    encounterId: 'ENC-1004',
    patientId: 'p-1',
    patientDisplayId: 'PT-0001',
    date: '2026-10-04T10:15:00Z',
    symptoms: 'Dry persistent cough, low grade fever, rhinorrhea',
    diagnosis: 'Acute Respiratory Infection',
    treatment: 'Steam inhalation, Cetirizine 10mg HS, Saline nasal drops',
    clinician: 'Dr. Rajesh Sharma',
    temperature: '99.5',
    bloodPressure: '122/80',
    status: 'completed',
    notes: 'Lungs clear on tele-auscultation.',
  },
  {
    id: 'enc-5',
    encounterId: 'ENC-1005',
    patientId: 'p-7',
    patientDisplayId: 'PT-0007',
    date: '2026-10-02T16:00:00Z',
    symptoms: 'Severe watery diarrhea (4 episodes), mild abdominal cramps',
    diagnosis: 'Acute Gastroenteritis',
    treatment: 'Oral Rehydration Salts (ORS) 3 sachets/day, Zinc 20mg OD x 14 days, Ciprofloxacin 500mg BD',
    clinician: 'Dr. Ananya Roy',
    temperature: '99.0',
    bloodPressure: '110/70',
    status: 'completed',
    notes: 'Assessed dehydration as mild. Water purification tablets distributed.',
  },
  {
    id: 'enc-6',
    encounterId: 'ENC-1006',
    patientId: 'p-3',
    patientDisplayId: 'PT-0003',
    date: '2026-09-28T11:00:00Z',
    symptoms: 'Chronic fatigue, pallor of conjunctiva, brittle nails',
    diagnosis: 'Iron Deficiency Anemia',
    treatment: 'Ferrous Ascorbate + Folic Acid OD after meals, nutritional counseling',
    clinician: 'Dr. Rajesh Sharma',
    temperature: '98.2',
    bloodPressure: '106/68',
    status: 'completed',
    notes: 'Hemoglobin reported at 8.9 g/dL. Dietary chart given.',
  },
  {
    id: 'enc-7',
    encounterId: 'ENC-1007',
    patientId: 'p-5',
    patientDisplayId: 'PT-0005',
    date: '2026-08-14T12:00:00Z',
    symptoms: 'Wheezing and chest tightness after exposure to dust',
    diagnosis: 'Bronchial Asthma',
    treatment: 'Salbutamol MDI with spacer, Budesonide 200mcg BID',
    clinician: 'Dr. Ananya Roy',
    temperature: '98.7',
    bloodPressure: '116/74',
    status: 'completed',
    notes: 'Inhaler technique demonstrated to patient and guardian.',
  },
  {
    id: 'enc-8',
    encounterId: 'ENC-1008',
    patientId: 'p-1',
    patientDisplayId: 'PT-0001',
    date: '2026-10-07T08:00:00Z',
    symptoms: 'Routine follow-up for respiratory recovery',
    diagnosis: 'Acute Respiratory Infection',
    treatment: 'Continued hydration, supportive care',
    clinician: 'Dr. Ananya Roy',
    temperature: '98.3',
    bloodPressure: '120/78',
    status: 'scheduled',
    notes: 'Telemedicine check-in scheduled for morning slot.',
  },
];

export const MOCK_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud-1',
    timestamp: '2026-10-07T07:45:10Z',
    user: 'Dr. Rajesh Sharma',
    role: 'ADMIN',
    action: 'LOGIN',
    entity: 'Session',
    entityId: 'SES-9821',
    status: 'completed',
    ipAddress: '103.21.144.12',
    details: 'Successful administrator authentication from District HQ',
  },
  {
    id: 'aud-2',
    timestamp: '2026-10-06T15:15:22Z',
    user: 'Dr. Rajesh Sharma',
    role: 'ADMIN',
    action: 'CREATE',
    entity: 'Encounter',
    entityId: 'ENC-1002',
    status: 'completed',
    ipAddress: '103.21.144.12',
    details: 'Created encounter for patient PT-0008 (Malaria)',
  },
  {
    id: 'aud-3',
    timestamp: '2026-10-06T09:35:05Z',
    user: 'Dr. Ananya Roy',
    role: 'CLINICIAN',
    action: 'CREATE',
    entity: 'Encounter',
    entityId: 'ENC-1001',
    status: 'completed',
    ipAddress: '115.111.45.89',
    details: 'Recorded telemedicine encounter for PT-0004',
  },
  {
    id: 'aud-4',
    timestamp: '2026-10-05T16:02:41Z',
    user: 'Pooja Verma',
    role: 'NURSE',
    action: 'UPDATE',
    entity: 'Patient',
    entityId: 'PT-0002',
    status: 'completed',
    ipAddress: '49.36.12.77',
    details: 'Updated vitals and contact clinic for PT-0002',
  },
  {
    id: 'aud-5',
    timestamp: '2026-10-05T08:12:00Z',
    user: 'Unknown (ip: 182.74.22.1)',
    role: 'ANONYMOUS',
    action: 'LOGIN_FAILED',
    entity: 'Auth',
    entityId: 'AUTH-FAIL-01',
    status: 'failed',
    ipAddress: '182.74.22.1',
    details: 'Invalid password attempted for clinician account',
  },
  {
    id: 'aud-6',
    timestamp: '2026-10-04T12:00:00Z',
    user: 'Pooja Verma',
    role: 'NURSE',
    action: 'UNAUTHORIZED_ACCESS',
    entity: 'AuditLog',
    entityId: 'SEC-LOG-01',
    status: 'failed',
    ipAddress: '49.36.12.77',
    details: 'Attempted to access restricted audit trail module without admin role',
  },
  {
    id: 'aud-7',
    timestamp: '2026-10-03T11:20:00Z',
    user: 'Dr. Rajesh Sharma',
    role: 'ADMIN',
    action: 'DELETE',
    entity: 'Encounter',
    entityId: 'ENC-0994',
    status: 'completed',
    ipAddress: '103.21.144.12',
    details: 'Purged duplicated encounter record upon clinician confirmation',
  },
];

export const MOCK_DASHBOARD_SUMMARY: DashboardSummary = {
  totalPatients: 8,
  totalEncounters: 38,
  encountersToday: 3,
  activeClinicians: 6,
  patientsChangePercentage: 12.5,
  encountersChangePercentage: 18.2,
  todayChangePercentage: 5.0,
};

export const MOCK_ENCOUNTER_TRENDS: Record<string, EncounterTrendPoint[]> = {
  today: [
    { date: '08:00', encounters: 1 },
    { date: '10:00', encounters: 2 },
    { date: '12:00', encounters: 3 },
    { date: '14:00', encounters: 2 },
    { date: '16:00', encounters: 1 },
  ],
  '7d': [
    { date: '01 Oct', encounters: 4, followUps: 1 },
    { date: '02 Oct', encounters: 6, followUps: 2 },
    { date: '03 Oct', encounters: 5, followUps: 1 },
    { date: '04 Oct', encounters: 7, followUps: 3 },
    { date: '05 Oct', encounters: 8, followUps: 2 },
    { date: '06 Oct', encounters: 11, followUps: 4 },
    { date: '07 Oct', encounters: 3, followUps: 1 },
  ],
  '30d': [
    { date: 'Week 1', encounters: 24, followUps: 8 },
    { date: 'Week 2', encounters: 31, followUps: 11 },
    { date: 'Week 3', encounters: 28, followUps: 9 },
    { date: 'Week 4', encounters: 38, followUps: 14 },
  ],
  '90d': [
    { date: 'Aug', encounters: 94, followUps: 32 },
    { date: 'Sep', encounters: 118, followUps: 41 },
    { date: 'Oct', encounters: 64, followUps: 22 },
  ],
  custom: [
    { date: 'Recent Range', encounters: 42, followUps: 15 },
  ],
};

export const MOCK_DIAGNOSIS_DISTRIBUTION: DiagnosisDistributionPoint[] = [
  { name: 'Acute Respiratory Inf.', count: 14, percentage: 35, color: '#2F8BC2' },
  { name: 'Type 2 Diabetes', count: 9, percentage: 22, color: '#3B82F6' },
  { name: 'Hypertension', count: 8, percentage: 20, color: '#0A9F6E' },
  { name: 'Malaria / Vector-borne', count: 5, percentage: 13, color: '#F2A900' },
  { name: 'Gastroenteritis', count: 4, percentage: 10, color: '#FF5C70' },
];

export const MOCK_AGE_DISTRIBUTION: AgeDistributionPoint[] = [
  { ageGroup: '0-14', male: 12, female: 15, other: 1 },
  { ageGroup: '15-29', male: 22, female: 28, other: 2 },
  { ageGroup: '30-44', male: 35, female: 38, other: 1 },
  { ageGroup: '45-59', male: 42, female: 39, other: 0 },
  { ageGroup: '60+', male: 28, female: 31, other: 1 },
];

export const MOCK_SEASONAL_TRENDS: SeasonalTrendPoint[] = [
  { month: 'May', viralRespiratory: 18, diabetesRelated: 24, vectorBorne: 6, gastrointestinal: 28 },
  { month: 'Jun', viralRespiratory: 22, diabetesRelated: 25, vectorBorne: 14, gastrointestinal: 35 },
  { month: 'Jul', viralRespiratory: 38, diabetesRelated: 27, vectorBorne: 45, gastrointestinal: 42 },
  { month: 'Aug', viralRespiratory: 44, diabetesRelated: 28, vectorBorne: 58, gastrointestinal: 38 },
  { month: 'Sep', viralRespiratory: 52, diabetesRelated: 29, vectorBorne: 42, gastrointestinal: 30 },
  { month: 'Oct', viralRespiratory: 36, diabetesRelated: 31, vectorBorne: 21, gastrointestinal: 22 },
];
